repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [ python ]
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [ python ]
      - id: ruff
        name: ruff linter
        entry: ruff
        language: python
        types: [ python ]
        args: [ --fix ]
      - id: toml-sort
        name: Sort TOML files
        entry: toml-sort
        language: python
        types: [toml]
        args: [--in-place, --sort-table-keys]
