version: "3.9"

networks:
  default:
    name: demo-fastapi
    driver: bridge

services:
  database:
    image: postgres:15-alpine
    container_name: app_db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5433:5432"
    networks:
      - default

  redis:
    image: redis:6.2-alpine
    container_name: app_redis
    ports:
      - "6379:6379"
    networks:
      - default

  api:
    build:
      context: ../
      dockerfile: docker/dev.Dockerfile
    container_name: app_api
    volumes:
      - "../app:/app/app"
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - database
      - redis
    networks:
      - default
